---
title: "Final Project"
author: "Daniil Finkel, Omar Boffil, Albert Ferguson"
date: '07/18/2020'
output:
  html_document:
    theme: readable
    toc: yes
  pdf_document: default
urlcolor: cyan
---

#### Team DOT:
- Daniilf2 - Daniil Finkel
- Oboffil2 - Omar Boffil
- Albertf2 - Albert Ferguson

# STAT 420: Project Proposal

### Predicting UPDRS (Unified Parkinson Disease Rating Scale) from Biomedical Voice Measurements of Individuals with Early Stage Parkinson’s Disease

Our chosen data file contains 22 attributes of 5875 observations. The attributes are:

- subject# - Integer that uniquely identifies each subject
- age - Subject age
- sex - Subject gender '0' - male, '1' - female
- test_time - Time since recruitment into the trial. The integer part is the
- number of days since recruitment.
- motor_UPDRS - Clinician's motor UPDRS score, linearly interpolated
- total_UPDRS - Clinician's total UPDRS score, linearly interpolated
- Jitter(%),Jitter(Abs),Jitter:RAP,Jitter:PPQ5,Jitter:DDP - Several measures of
- variation in fundamental frequency
- Shimmer,Shimmer(dB),Shimmer:APQ3,Shimmer:APQ5,Shimmer:APQ11,Shimmer:DDA
- Several measures of variation in amplitude
- NHR,HNR - Two measures of ratio of noise to tonal components in the voice
- RPDE - A nonlinear dynamical complexity measure
- DFA - Signal fractal scaling exponent
- PPE - A nonlinear measure of fundamental frequency variation

The dataset was created in collaboration by Intel, Oxford and several medical centers to study patient Parkinson’s progression. 

The data set is provided by UCI, available here:  
https://archive.ics.uci.edu/ml/datasets/Parkinsons+Telemonitoring

Recently, machine learning has seen significantly more use in healthcare. Through this project and dataset, we seek to get a better understanding of just how and why machine learning pairs so well with medical data.

We have successfully loaded the data into R. A preview of the data is below:

```{r}
library(readr)
data = read_csv("parkinsons_updrs.csv")
head(data$total_UPDRS)
```

